Repository keyvankhademi/cosc-499-team-ex, pull requests merged in 2022-09, with the labels that each got.

#6 Set Environment Variables
  .github/generate_report.py
  .github/workflows/stats.yml
Labels: chore

#3 Updated README
  README.md
Labels: chore, exploration

#10 add bogo sort
  bogo_sort.py
Labels: task

#9 add .gitignore
  .gitignore
Labels: chore

#12 add buble sort
  bubble_sort.py
Labels: task

#17 Implement Merge Sort
  merge_sort.py
Labels: task

#20 Test merge sort
  tests/merge_sort_tests.py
Labels: task

#18 edited readme to make it look better
  README.md
Labels: task

#21 added test for bubble sort
  bubble_sort_test.py
Labels: task

#19 Added selection sort code and the corresponding tests.
  selection_sort.py
  tests/selection_sort_tests.py
Labels: task

#23 add bogo sort test
  tests/bogo_sort_tests.py
Labels: task

#25 update readme
  README.md
Labels: chore

#27 move bubble sort test to the right folder
  tests/bubble_sort_test.py
Labels: chore
